CleverGameDev/LetterJam

Procfile, package-lock.json, package.json
Heroku already builds for us; removing it from the Procfile.
Need serve in production; moving it to prod dependencies
=> Cleanup setup

src/scripts/objects/playStateText.ts, src/scripts/scenes/endScene.ts, src/scripts/scenes/lobbyScene.ts, src/scripts/scenes/mainScene.ts, src/scripts/scenes/setupScene.ts
Just some templates for scenes we will build, and a basic implementation of changing game states.
=> Game State and Scenes

src/scripts/game.ts, src/scripts/objects/phaserLogo.ts, src/scripts/objects/playStateText.ts, src/scripts/scenes/endScene.ts, src/scripts/scenes/gameScene.ts, src/scripts/scenes/lobbyScene.ts, src/scripts/scenes/preloadScene.ts, src/scripts/scenes/setupScene.ts
Allow clicking on a sprite to move among the scenes.
In the GameScene, click on the left sprite to move among the substates of that scene.
--
Also: the below link is pretty useful reading on how to think about scenes in phaser. It's possible e.g. to run multiple scenes at once.
https://rexrainbow.github.io/phaser3-rex-notes/docs/site/scenemanager/
=> move among scenes by clicking on sprite

src/server/server.ts
Also ran
```
heroku config:set IS_HEROKU=true -a letterjam
```
=> try using port 443 on heroku

src/client/scripts/lib/discuss.ts
Some client-side groundwork for discussing clues. Will need to follow-up with the server changes to support managing the state of the world, but I realize we probably do want to do some work to set up the world. Otherwise, the game loop is hard to test.
I added some types to help me build out my stuff but I figure we should put this somewhere shared since the same types will need to be referenced elsewhere.
=> Support logic for discussing clues

run_local.sh, src/server/server.ts
=> Run local pt2

src/client/scripts/lib/discuss.ts, src/server/server.ts, src/shared/models.ts, webpack/webpack.common.js
* Send clues and votes to server
* Add src as an aliased import path
=> Discuss pt2

src/client/scripts/objects/guessingSheet.ts, src/client/scripts/scenes/gameScene.ts
Render a hacky guessing sheet. 
Show/hide by clicking the button in the bottom left.
=> add guessingsheet object and display in gameScene

.gitignore, src/client/scripts/objects/flower.ts, src/client/scripts/scenes/gameScene.ts
Flower that is not visually a flower!
=> Add Flower

package-lock.json, package.json, src/client/scripts/game.ts, src/client/scripts/objects/activeClues.ts, src/client/scripts/objects/dialog.ts, src/client/scripts/objects/phaserLogo.ts, src/client/scripts/scenes/endScene.ts, src/client/scripts/scenes/gameScene.ts, src/client/scripts/scenes/lobbyScene.ts, src/client/scripts/scenes/preloadScene.ts, src/client/scripts/scenes/setupScene.ts, src/server/server.ts, src/shared/models.ts, webpack/webpack.common.js
* Added some UI elements so we can actually see the Discuss steps in action. Hardcoded the game state and will fix in a separate PR.
* Fixed some preload stuff. I think the preload happens per scene, which is why we were seeing black squares just bobbing up and down since we were only preloading on the Preload scene before.
* Turned off physics on our images. It was slowing things down and we don't really need it yet.
Notes:
* We still need to clear previous active clues and update the visible letters
* The rendering is off. Not sure if we can layer things on top of one another or if we should manage the visibility/active state of everything we render in a scene.
=> Discuss ui elements

src/client/scripts/lib/setup.ts, src/shared/constants.ts
Just some basic numbers and utility functions to help us get the game started. Will actually incorporate this into a scene in a separate PR but I figure this is worth pushing to master in case anyone wants to build on top of it.
=> Deck setup

package-lock.json, package.json, run_local.sh, src/server/server.ts
* Set up ts-node server so we can use Typescript on the server code
* Add hot reloading to server code via nodemon
=> Use ts-node for Express server so we can use TS

package-lock.json, package.json, src/client/scripts/scenes/gameScene.ts, src/client/scripts/scenes/lobbyScene.ts, src/server/lib/gameUtils.ts, src/server/lib/setup.ts, src/server/server.ts, src/shared/models.ts, webpack/webpack.common.js
https://trello.com/c/R9w5wZlu/92-letterjam-how-to-maintain-a-persistent-player-id
Approach:
- Use express-sessions. This creates a session as a browser cookie that
persists across page loads.
- Use another library to allow accessing express sessions in SocketIO.
- Write to SQLite DB to persist across server restarts
- Use the `session.id` as the playerID.
--
Beyond this change, I did some refactoring. I moved players into the
`ServerGameState`.
Players are represented via a `Map`, but we can change it to a regular
ol' object `{}` if the `Map` is annoying. You *must* use get/set methods
on the map for it to work.  Otherwise you set properties on the map
object, which isn't what you want. :)
=> Persistent player ID on page reloads

package-lock.json, src/server/server.ts
Now when you submit a clue, everyone gets it! 🎈
=> Bug Fix: Clues go to everyone now!

src/server/lib/game.ts, src/server/server.ts
so far.. move core game + socketIO out of `server.ts`
=> refactorin

src/client/scripts/lib/discuss.ts, src/client/scripts/scenes/endScene.ts, src/client/scripts/scenes/gameScene.ts, src/client/scripts/scenes/lobbyScene.ts, src/client/scripts/scenes/preloadScene.ts, src/client/scripts/scenes/setupScene.ts, src/server/lib/game.ts, src/server/lib/gameUtils.ts, src/shared/events.ts, src/shared/models.ts
https://trello.com/c/poDrQyWl/94-letterjam-model-all-client-server-comms-as-typed-events
and a quick bug fix https://github.com/CleverGameDev/LetterJam/pull/39/commits/295be876f4a229a8b1fcfce4cfe0cac5504cafae
=> Refactor #3: Let there be (event) types

package-lock.json, package.json, src/client/scripts/game.ts, src/client/scripts/objects/dialog.ts, src/client/scripts/scenes/gameScene.ts, src/client/scripts/scenes/lobbyScene.ts
https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#install-from-npm-package
=> Use rexui package from npm package

src/server/lib/core.ts, src/server/lib/playerUtils.ts, src/server/lib/scenes/end.ts, src/server/lib/scenes/game.ts, src/server/lib/scenes/index.ts, src/server/lib/scenes/lobby.ts, src/server/lib/scenes/setup.ts
Add teardown functions
Move setup and teardown into scene files
=> Move setup and teardown into scene files

src/client/scripts/lib/discuss.ts, src/client/scripts/objects/guessingSheet.ts, src/client/scripts/objects/playStateText.ts, src/client/scripts/scenes/gameScene.ts, src/client/scripts/scenes/preloadScene.ts, src/server/lib/core.ts, src/server/lib/gameState.ts, src/server/lib/scenes/game.ts, src/shared/constants.ts, src/shared/events.ts, src/shared/models.ts
* Supports updating guessing sheet with clue word based on what the clue giver would see
* Supports progressing the game by denoting if every player is "ready"
* Allows players to advance their visible letter
=> Update guessing sheet

src/client/scripts/objects/activeClues.ts
=> ActiveClues: improve readability

src/client/scripts/lib/discuss.ts, src/client/scripts/objects/activeClues.ts, src/client/scripts/objects/dialog.ts, src/client/scripts/objects/flower.ts, src/client/scripts/objects/fpsText.ts, src/client/scripts/objects/guessingSheet.ts, src/client/scripts/objects/playStateText.ts, src/client/scripts/objects/stand.ts, src/client/scripts/scenes/endScene.ts, src/client/scripts/scenes/gameScene.ts, src/client/scripts/scenes/lobbyScene.ts, src/client/scripts/scenes/preloadScene.ts, src/client/scripts/scenes/setupScene.ts, src/server/lib/core.ts, src/server/lib/gameState.ts, src/server/lib/playerUtils.ts, src/server/lib/scenes/end.ts, src/server/lib/scenes/game.ts, src/server/lib/scenes/index.ts, src/server/lib/scenes/lobby.ts, src/server/lib/scenes/setup.ts
* Add more typing to changes from https://github.com/CleverGameDev/LetterJam/pull/45
* Fix some lint warnings related to typing
=> Type cleanup

src/client/scripts/objects/activeClues.ts, src/client/scripts/scenes/gameScene.ts, src/server/lib/gameState.ts, src/server/lib/scenes/game.ts
https://trello.com/c/FDRyuuuq/114-npcs-should-progress-their-letters-if-used
=> Advance npc letters (+ refactor advancePlayState logic)

package-lock.json, package.json, src/client/scripts/objects/activeClues.ts
https://trello.com/b/hmdxVEYb/gamedev
=> bug: fix double-counting when giving hint

src/client/scripts/objects/activeClues.ts, src/client/scripts/objects/guessingSheet.ts, src/client/scripts/objects/table.ts, src/client/scripts/scenes/gameScene.ts, src/shared/constants.ts
Change active clues and guessing sheet to use grid table instead of text version of matrix.
Outstanding tasks:
* Mark highest vote player in active clues sheet
* Provide ability to put notes for guessing sheet
* Provide ability to guess final word in guessing sheet
=> Table display

src/client/scripts/scenes/gameScene.ts, src/server/lib/gameState.ts, src/server/lib/scenes/game.ts, src/shared/models.ts
Also made a few small improvements to "I am ready" usability, see commits
=> Show "I'm ready" in the UI

src/client/scripts/objects/dialog.ts, src/client/scripts/scenes/gameScene.ts, src/client/scripts/scenes/lobbyScene.ts
https://trello.com/c/7OP6oRpt/122-dialog-for-give-clue-should-clear-text-input-each-round
=> Reset dialogs

src/client/scripts/objects/activeClues.ts, src/client/scripts/objects/dialog.ts, src/client/scripts/objects/guessingSheet.ts, src/client/scripts/objects/util.ts, src/client/scripts/scenes/gameScene.ts, src/client/scripts/scenes/lobbyScene.ts
https://trello.com/c/WDwXWpia/126-only-allow-one-modal-at-a-time
=> improve UX for modal interactions

src/client/scripts/objects/activeClues.ts, src/client/scripts/scenes/gameScene.ts
* Add not ready to UI
* Add some color to ready/not ready
* Move winning vote indicator to active clues table
=> Ui iteration 1

src/client/scripts/scenes/gameScene.ts
fixes https://trello.com/c/wHLQKLtQ/131-give-clue-dialog-should-be-in-foreground
=> bug: Give Clue dialog should be in foreground

src/client/scripts/scenes/lobbyScene.ts
same idea as:
https://github.com/CleverGameDev/LetterJam/pull/64
=> lobbyScene dialog to foreground

src/client/scripts/scenes/gameScene.ts
Open dialogs automatically during play state transitions.
http://g.recordit.co/MIfl8sMbKX.gif
=> Auto display dialogs when going through play states

.eslintignore, jest.config.js, package-lock.json, package.json, src/server/lib/gameState.test.ts, src/server/lib/gameState.ts, tsconfig.json, webpack/webpack.common.js
Adding jest so we can write unit tests about server game state. Testing edge cases that occur late in a game is annoying via the UI, so this should make that easier!
=> Add jest + refactor "assign letters"

src/client/scripts/scenes/gameScene.ts
It was getting annoying opening the active clues again every time after giving a clue -- make it auto open.
=> Re-open active clues after giving clue

src/client/scripts/objects/activeClues.ts, src/server/lib/gameState.ts, src/shared/models.ts
Add a checkmark next to Vote to indicate which clue the user voted for.
=> Indicate vote

src/client/scripts/objects/activeClues.ts, src/client/scripts/scenes/gameScene.ts
Disable the Give Clue button when in Interpret Hint state; re-enables it when in Discuss state.
=> Disable give clue

src/server/lib/gameState.test.ts, src/server/lib/gameState.ts
https://trello.com/c/w4S2kulX/139-bug-in-the-winning-vote-logic-where-1-2
=> fix getPlayerWhoWonVote

src/server/lib/gameState.test.ts, src/server/lib/gameState.ts
https://trello.com/c/ppmcwSfx/124-clue-tokens-improvements
The previous logic was simplified. This logic follows the Letterjam
rulebook.
=> improve clue token logic

src/client/scripts/scenes/endScene.ts, src/server/lib/gameState.ts, src/shared/models.ts
https://trello.com/c/xELJUyAJ/125-endscene
=> endScene: show guess vs actual final word

src/client2/package-lock.json, src/client2/package.json, src/client2/src/ActiveClues.tsx, src/client2/src/App.tsx, src/client2/src/Flower.tsx, src/client2/src/GameScene.tsx, src/client2/src/LobbyScene.tsx, src/client2/src/NavBar.tsx, src/client2/src/index.tsx
- react-ui baby steps
- starting effort on ActiveClues
- add vote interaction in ActiveClues
=> React Client: game scene -- first steps

src/client2/src/GameScene.tsx, src/client2/src/Stands.tsx, src/client2/src/index.tsx
- GameScene: add letter stands
- add a MUI theme
=> React Client: add stands to game scene

src/client2/src/GuessingSheet.tsx
=> GuessingSheet: add color

src/client2/src/App.tsx, src/client2/src/ui/LobbyScene.tsx, src/client2/src/ui/SetupScene.tsx
=> Add LobbyScene and SetupScene

src/client2/src/ui/LobbyScene.tsx
=> New lobby scene design

src/server/lib/core.ts, src/server/lib/gameState.ts, src/server/lib/scenes/lobby.ts
allow players to leave if LobbyScene. fixes:
https://trello.com/c/8JwHD7nB/107-letterjam-given-persistent-ids-figure-out-how-a-player-leaves-lobby
also a quick UX/validation improvement... player name must be non-empty
=> players can leave lobby
